default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distrubtion do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
      app: "1:167743183066:android:dc81667676baf704cf6de3",
      firebase_cli_token:"1//03HkijjmdTZPhCgYIARAAGAMSNwF-L9IrErntZEq0Nc1mouIwGTEX9TEFOI_CcyzhcaqqnXltaw__j-Vy6GE7qnhWfITURbAtG5U",
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
      testers:"jomohamed87@gmail.com",
      release_notes: "First Fastlane Firebase App Distribution"
    )
  end
end
