name: Android Fastlane with Firebase App Distribution Workflow #Optional

on:
  push:
    branches:
      - master

jobs:
  distribute_to_firebase: #Optional Naming
    runs-on: ubuntu-latest # For android Deployment , on Ios it will be macos-latest
    steps:
    - name: Checkout my repo code #Optional like a comment
      uses: actions/checkout@v2
    
    - name: Set up JDK 11 # For android Deployment , it Needs Java 11 as Stable Version
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable

    - name: Setup Ruby #For Fastlane
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.2.3"
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically , for fastlane to make it faster
        working-directory: android # to report the working directory for fastlane as i make (cd android) in Terminal
        
    - name: Build and Distribute App
      env:
        FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
      run: |  # bundle exec fastlane android firebase_distribution for making process faster
        bundle exec fastlane android firebase_distribution 
      working-directory: android

